export const GET_Movies_REQUEST = "GET_Movies_REQUEST";
export const GET_Movies_SUCCESS = "GET_Movies_SUCCESS";
export const GET_Movies_FAILURE = "GET_Movies_FAILURE";

export const GET_MOVIE_DETAILS_REQUEST = "GET_MOVIE_DETAILS_REQUEST";
export const GET_MOVIE_DETAILS_SUCCESS = "GET_MOVIE_DETAILS_SUCCESS";
export const GET_MOVIE_DETAILS_FAILURE = "GET_MOVIE_DETAILS_FAILURE";
